### ISSUE TITLE
Disable Cyclic Nether and End ore generation in favor of Nether Metals and End Metals

### ISSUE THREAD

**Issue by notcake** [notcake/glua-minecraft-planning#12]

**Comment by mcd1992** [comment]
Cyclic metals are disabled by default now it seems.

`cyclic_ores.cfg`
```
_global_ {
    # False means all are disabled no matter what.  True means each ore uses its own true/false to exist.   [default: false]
    B:globalOverride=false
}

```

**Comment by notcake** [comment]
It's also false in my copy of the cyclic config from last year. Can you double check in the nether?

**Comment by mcd1992** [comment]
I double checked and didn't see any in the nether. But I do see cyclic lapis and gold in the end for some reason.

**Comment by notcake** [comment]
Sounds suspicious

**Comment by mcd1992** [comment]
The dense ones were still spawning as well though. Is there a oredict issue where we only want one dense ore type?

**Comment by notcake** [comment]
Wait what. Cyclic dense ores?

**Comment by mcd1992** [comment]
Err it was regular ore, but owned by cyclic. Redstone, lapis and gold. 

The other mod ores are still showing up in the end though.

**Comment by notcake** [comment]
`cyclicmagic.cfg`?
```
        # Generate ore in the end.
        B:"End Ore"=true

        # These dimension ores (nether and end) have a chance to spawn endermites or silverfish
        B:"Infested Ores"=true

        # Generate ore in the nether.
        B:"Nether Ore"=true
```
