### ISSUE TITLE
Add Roost for more efficient chicken farming

### ISSUE THREAD

**Issue by notcake** [notcake/glua-minecraft-planning#20]
https://www.curseforge.com/minecraft/mc-mods/roost

**Comment by SwadicalRag** [comment]
if only this was accepted in 2018!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by SwadicalRag** [comment]
we could've made avaritia stuff

**Comment by notcake** [comment]
what if we kissed

**Comment by notcake** [comment]
in an RFTools dimension

**Comment by SwadicalRag** [comment]
:woke:
