### ISSUE TITLE
Investigate why Dense T Ores and Nether T Ores do not process correctly

### ISSUE THREAD

**Issue by notcake** [notcake/glua-minecraft-planning#3]

**Comment by mcd1992** [comment]
Processs in? I'm guessing the dust things?

**Comment by notcake** [comment]
They smelted into a single nugget or something stupid like that last year.

**Comment by notcake** [comment]
Nether Metals and Dense Metals will be replaced with Ore Stone Variants in #47

**Comment by notcake** [comment]
The Dense Metals ore have no processing recipes or ore dictionary entries.
The nether ores which were broken were probably from Cyclic, whose nether ores drop nuggets and smelt into single ingots. Cyclic nether ores were disabled in #12.

Nether Metals do not generate unless Base Metals is installed, despite the mod description claiming it has no dependencies on Base Metals. Nether Metals ores process just fine.
