### ISSUE TITLE
Add TorchMaster

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#49]
**Mod URL:** https://www.curseforge.com/minecraft/mc-mods/torchmaster
**Description (within 120 characters):** Adds in specialised torches that can prevent the spawns of nearby mods. Also adds in a torch that can light up a very large area.

| Code Quality                       | Values     |
|------------------------------------|------------|
| Open Source (Y/N)                  | Y          |
| Git tree quality (please rate)     | :star::star::star:☆☆      |
| General code quality (please rate) | unassessed |

| Mod Quality                           | Values     |
|---------------------------------------|------------|
| Performance (please rate)             | unassessed |
| Design / UI (please rate)             | N/A        |
| Compatibility with current mods (Y/N) | unassessed |

**Comment by notcake** [comment]
For controlling mobs, the modpack already has:
* Interdiction Pulsar (Cyclic)
* Interdiction Torches (Reliquary)
* Peace Candle (Random Things)
* Crushed Obsidian (Railcraft)

The first two repel mobs and the last two prevent mobs from spawning

**Comment by SwadicalRag** [comment]
Agreed, closing
