### ISSUE TITLE
Add OverloadedArmorBar

### ISSUE THREAD

**Issue by notcake** [notcake/glua-minecraft-planning#50]
**Mod URL:** https://www.curseforge.com/minecraft/mc-mods/overloaded-armor-bar
**Description (within 120 characters):** The extra hearts display but for armor

| Code Quality                       | Values     |
|------------------------------------|------------|
| Open Source (Y/N)                  | Y          |
| Git tree quality (please rate)     | :star:☆☆☆☆      |
| General code quality (please rate) | [e](https://github.com/Tfarcenim/OverloadedArmorBar/commit/d6f209281f90b6fd26a86da3d4dc3f43078978e2) |

| Mod Quality                           | Values     |
|---------------------------------------|------------|
| Performance (please rate)             | unassessed |
| Design / UI (please rate)             | yes        |
| Compatibility with current mods (Y/N) | unassessed |

**Comment by SwadicalRag** [comment]
👍 
 e
