### ISSUE TITLE
Add AttributeFix

### ISSUE THREAD

**Issue by notcake** [notcake/glua-minecraft-planning#51]
**Mod URL:** https://www.curseforge.com/minecraft/mc-mods/attributefix
**Description (within 120 characters):** Removes the 30 Armor and 20 Armor Toughness limit

| Code Quality                       | Values     |
|------------------------------------|------------|
| Open Source (Y/N)                  | Y          |
| Git tree quality (please rate)     | ⭐⭐ |
| General code quality (please rate) | ⭐⭐⭐⭐ |

| Mod Quality                           | Values     |
|---------------------------------------|------------|
| Performance (please rate)             | unassessed |
| Design / UI (please rate)             | N/A |
| Compatibility with current mods (Y/N) | unassessed |

**Comment by SwadicalRag** [comment]
Does this fix cyclic?

**Comment by notcake** [comment]
What's wrong with Cyclic?

**Comment by SwadicalRag** [comment]
hearts

**Comment by notcake** [comment]
Nope, only Cyclic can fix itself

**Comment by SwadicalRag** [comment]
F
