### ISSUE TITLE
Global XP/XP Tome

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#64]
1. https://www.curseforge.com/minecraft/mc-mods/global-xp
2. https://www.curseforge.com/minecraft/mc-mods/xp-tome

Both mods add in an item to store exp. #1 adds in a block that can be broken with exp saved as NBT data in the item drop, whereas #2 is just a held item and not a block.

Given the dozens of other mods we already have which can store exp, I vote to remove both of these mods. Conservatively, if I had to pick one of these two mods, I vote for #2 since its code is clean, commented and minimal and should therefore have a minimal performance impact

**Comment by notcake** [comment]
NB: We don't have OpenBlocks or Ender IO this year so storing experience is going to be a pain.

**Comment by Lixquid** [comment]
Also XP Tome counts as a book and can therefore be stored in the akashic tome, making it slightly more useful

**Comment by SwadicalRag** [comment]
> NB: We don't have OpenBlocks or Ender IO this year so storing experience is going to be a pain.

I believe cyclic (?) has equivalent exp storage systems
