### ISSUE TITLE
Woot/Tiny Mob Farm

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#69]
1. https://www.curseforge.com/minecraft/mc-mods/tiny-mob-farm
2. https://www.curseforge.com/minecraft/mc-mods/woot

Both add in entity-free mob farms. Woot is better known and more comprehensive so I vote we keep woot.

**Comment by notcake** [comment]
The tiny mob farms are cute though. And probably not as big a pain in the ass to create as Woot farms.

**Comment by Lixquid** [comment]
Yeah tiny mob farms are good early game mob farms: they only last for a certain amount of time per mob put in them, so they're not a direct replacement for woot

**Comment by SwadicalRag** [comment]
I'm okay with keeping both, but I thought it best to flag this in an official channel

**Comment by SwadicalRag** [comment]
No further problems here, but still receptive to any discussion
