### ISSUE TITLE
Solar Flux Reborn/Solar Generation

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#70]
1. https://www.curseforge.com/minecraft/mc-mods/solargeneration
2. https://www.curseforge.com/minecraft/mc-mods/solar-flux-reborn

how many solar panel mods does glua need??

I vote we keep solar flux reborn since it seems better in terms of cross-mod integration

**Comment by notcake** [comment]
Both mods have recursive recipes (think Simply Jetpacks 2).
Solar Flux Reborn has up to 2xFE/t upgrades
Solar Generation has icons that look like they were drawn in mspaint.
