### ISSUE TITLE
Farmers make do but we have too many mods to do farming

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#71]
✔️ = Keep, ❌ = Yeet this mod out of our pack

1. ❌ https://www.curseforge.com/minecraft/mc-mods/xl-food-mod/
2. ❌ https://www.curseforge.com/minecraft/mc-mods/the-veggie-way/
3. ❌ https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition
4. ❌ https://www.curseforge.com/minecraft/mc-mods/simple-farming
5. ✔️ https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops/
6. ✔️ https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core/
7. ✔️ https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees/
8. ✔️ https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads
9. ✔️ https://www.curseforge.com/minecraft/mc-mods/planttech-2

**Comment by notcake** [comment]
Simple Farming adds curry
Sneaky will be devastated

**Comment by Lixquid** [comment]
love me curry
love me mining
love me dakis
'ate working
'ate badger
'ate building

this is glua mc if you dont like it you can GET OUT

**Comment by SwadicalRag** [comment]
I'm okay with keeping simple farming, I was being extra judicious with mod culling

**Comment by SwadicalRag** [comment]
Problem solved therefore we can close this issue, but as always still open for further discussion
