### ISSUE TITLE
Building Gadgets/Prefab/BetterBuildersWands

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#73]
1. https://www.curseforge.com/minecraft/mc-mods/building-gadgets
2. https://www.curseforge.com/minecraft/mc-mods/prefab
3. https://www.curseforge.com/minecraft/mc-mods/better-builders-wands

building gadgets has a copy paste tool and is absolutely superior. I vote we get rid of prefab

**Comment by notcake** [comment]
TODO: Test if Surface Mode does everything that BetterBuildersWands does

**Comment by notcake** [comment]
Players have been using Prefab for instant preset house creation and not copy paste/templating

**Comment by notcake** [comment]
Building Gadgets' Surface mode has a small range limit and is a poor replacement for builders wands.
However the Copy-Paste gadget does not seem to have a small limit below 50 blocks, so works as a wand but with more walking around to set the bounds.

**Comment by Lixquid** [comment]
Builder's Gadgets is absolutely a useful mod and should stay.

Prefab is just a less faffy way to make common structures so I vote we keep it in.

Big Beautiful Wands doesn't even have a version for 1.15 does it?

**Comment by SwadicalRag** [comment]
I did not know people were using prefab, in which case there is merit to keeping it

I'm happy to keep both, since as you said, builder's gadgets does not serve exactly the same niche as prefab

**Comment by SwadicalRag** [comment]
There are no further problems to be addressed here, but as always, discussion is still welcome
