### ISSUE TITLE
Mekanism cardboard/Packing Tape

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#74]
https://www.curseforge.com/minecraft/mc-mods/packing-tape

y'all heard of mekanism's cardboard boxes?

**Comment by notcake** [comment]
Are there non-Mekanism ways to obtain sawdust?

**Comment by notcake** [comment]
Compatible sawdust can be created using Immersive Engineering, Mekanism and Thermal Expansion machines
