### ISSUE TITLE
MineMenu/Tool Belt - semi duplicated functionality

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#80]
1. https://www.curseforge.com/minecraft/mc-mods/minemenu
2. https://www.curseforge.com/minecraft/mc-mods/tool-belt

The only difference is that tool belt gives you additional inventory slots to store your tools, whereas minemenu is purely a UI facelift.

If we keep one, it makes sense to keep tool belt and remove minemenu. That way this feature is "opt in" and actually has a benefit to the player.

**Comment by Lixquid** [comment]
Don't get rid of minemenu, it's actually useful since it can alias multiple commands like `/trash` or Mine&Slash hub or other keybinds to one key.

ToolBelt is a fucking faff and I wouldn't be sad to see it gone. Just use a backpack.
