### ISSUE TITLE
InstantUnify is incompatible with 1.15 - try UniFix instead

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#81]
❎ https://www.curseforge.com/minecraft/mc-mods/instantunify
✅ https://www.curseforge.com/minecraft/mc-mods/unifix

N.B. I am aware we have [JAOPCA](https://www.curseforge.com/minecraft/mc-mods/jaopca) which allows ore unification between some mods and [Polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph) which allows you to choose different outputs for the same recipe in a crafting table.

**Comment by notcake** [comment]
InstantUnify turns the 6 different types of copper ore into the same type of copper ore as you mine them.
Unifix looks like it does recipes instead

Unifix is still needed since smelting the 6 copper ore types produces 3 different copper ingot types

**Comment by notcake** [comment]
With Unifix installed, smelting the 7 different types of copper ore produces a single type of copper ingot
