### ISSUE TITLE
Chisel - incompatible

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#89]
https://www.curseforge.com/minecraft/mc-mods/chisel/

Unfortunate. If not for chisel's absence, I would have culled all of the pointless decorative block mods from this modpack

**Comment by notcake** [comment]
There is a 1.15 version in the works: https://ci.tterrag.com/job/Chisel/job/1.15-dev/

Left enabled intentionally so that the 1.15.2 version is automatically picked up for next year.

**Comment by mcd1992** [comment]
>expecting curseforge to exist after overwolf purchasing this year
