### ISSUE TITLE
YAMDA/Buuz135s Dimensional Worlds

### ISSUE THREAD

**Issue by SwadicalRag** [notcake/glua-minecraft-planning#90]
1. https://www.curseforge.com/minecraft/mc-mods/buuz135s-dimensional-worlds/
2. https://www.curseforge.com/minecraft/mc-mods/yamda/

pick one

**Comment by mcd1992** [comment]
YAMDA DIMs are all solid worlds with no cavegen. The other one is overworld (with the good cavegen) and always day, but no nether DIM.

**Comment by notcake** [comment]
Advanced Mining Dimension is the one with solid worlds.
Both YAMDA and Buuz135s Dimensional Worlds are overworld and always day.
YAMDA has no caves while Buuz135s Dimensional Worlds does.

YAMDA crashes me consistently when entering a new dimension requiring worldgen.
